### PR TITLE
 Improvement: parsing and setting heart rate and cadence from TCX #6

### PR DESCRIPTION
**Pull request by matteoquintiliani**
Resolve issue #6

### CODE REVIEW

**Comment by cwarwicker** [comment]
Hi, do you have a .TCX file with heartrate and cadence, so I can test it? My device doesn't give me those elements.

**Comment by matteoquintiliani** [comment]
Hi, I attach a TCX file created by Polar device.

[test_2018-11-04_09-12-38.tcx.gz](https://github.com/cwarwicker/Waddle/files/2556974/test_2018-11-04_09-12-38.tcx.gz)

**Comment by kyoden** [comment]
Hi,
You should be add the function `getAvgHeartRate` and `getMaxHeartRate` in the class `Activity`. It would be very nice.

**Comment by cwarwicker** [comment]
Hi,

I forgot to merge the pull requests I had, so have been going through them. I think another one I merged has the same thing in yours for the TCXParser, looking for some kind of extension.

If you're still using this, could you have a quick look and see if your stuff still needs merging in, or if it was covered in the previous one I merged?

Thanks.

**Comment by ahoogerheide** [comment]
Would you be able to merge this. Looking at this it is not available in the TCXParser with any of the previous merges. I would like to use the cadence functionality of TCX files.

**Comment by cwarwicker** [comment]
Yeah I'll go through the merge requests again.

**Pull request merged**
